### ISSUE TITLE
allow emojis to stand by themselves

### ISSUE THREAD

**Issue by mt-caret** [textlint-ja/textlint-rule-ja-no-mixed-period#2]
「合格しました。🎉」のような文章の「🎉」も文字として認識されるのか、 「文末が"。"で終わっていません。」と怒られてしまいます。

再現方法:
```
$ echo "合格しました。\n🎉" > test.md
$ textlint --rule ja-no-mixed-period test.md
```

Issueとは特に関係ありませんが、再現を試みていた時に
```
$ echo "合格しました。\n🎉" | textlint --stdin --rule ja-no-mixed-period
```
を実行したところ、正常として認識されてしまいます。
```
$ echo "合格しました" | textlint --stdin --rule ja-no-mixed-period
```
とするとja-no-mixed-periodが正常に発火します。

**Comment by azu** [comment]
ご報告ありがとうございます。
やや意図した動作でもありますが、次のような修正が考えられそうです。

任意の文字?(正規表現)を文末に置いて良い文字としてオプションで設定できるようにする。
(ただ、絵文字全般という定義難しい感じがします。 `:+1` なども許容したい場合は1文字だけじゃないので、正規表現で指定出来るようにしないといけなさそう)

現在は例外的に文末に置いても良い文字が幾つか定義されています。
これを設定から自由に追加出来るようにするかんじですね。

` /[!?！？\)）」』]/`

- https://github.com/textlint-ja/textlint-rule-ja-no-mixed-period/blob/954bbfc6aee5fbd95bfcb18ed7d784ffb1879a60/src/textlint-rule-ja-no-mixed-period.js#L48

**Comment by azu** [comment]
> Issueとは特に関係ありませんが、再現を試みていた時に

```
$ echo "合格しました。\n🎉" | textlint --stdin --rule ja-no-mixed-period
```

これはパスするのはややこしいですが、正しい動作ですね。

- textlintはデフォルト(拡張子などの情報が何もない = 標準入力) はplain textとして扱う
- plain textは改行ごとに パラグラフが分かれているという認識になっている
- パラグラフに日本語が含まれない場合は、そのパラグラフを無視する ( 🎉 だけのパラグラフがあるという認識) という処理がルールに入っている。

ということが起きています。

次のようにMarkdownとして認識させると、恐らくエラーとして検出されます。
(markdownのパラグラフ`<p>`は空改行で区切ったときにできるからですね)

```
$ echo "合格しました。\n🎉" | textlint --stdin --stdin-filename test.md --rule ja-no-mixed-period

**Comment by mt-caret** [comment]
迅速かつ丁寧なご対応ありがとうございます。

> 現在は例外的に文末に置いても良い文字が幾つか定義されています。
> これを設定から自由に追加出来るようにするかんじですね。

ですね。ぱっと調べてみたところ、[うまい感じに絵文字にマッチする正規表現ライブラリ](https://github.com/mathiasbynens/emoji-regex)を見つけたので、導入したPRを飛ばしてもよろしいでしょうか？

**Comment by azu** [comment]
はい。
基本的には全部オプションで変更可能にしていきたいので、

- `allowEmojiAtEnd` という 真偽値のオプションを追加する
- `allowEmojiAtEnd` が true ならば、絵文字の正規表現にマッチするものが末尾ならば無視する
  - https://github.com/textlint-ja/textlint-rule-ja-no-mixed-period/blob/954bbfc6aee5fbd95bfcb18ed7d784ffb1879a60/src/textlint-rule-ja-no-mixed-period.js#L48 と同じやり方
- [ ] `allowEmojiAtEnd` の デフォルト値は `true` ? (どっちがいいんだろ?)

という感じにしていただけると助かります。

-----

(これに加えて、 末尾にある任意のものを無視する設定を追加できれば、大体のことはオプションとして解決できるようになるかなと思います。絵文字もこのオプションでやってという形でもいいのですが、あまりに正規表現が難しいので別オプションが妥当な気がします。)

```
allowWordAtEnd: [
  "好きな文字列",
  "/好きな正規表現$/"
]
```

**Comment by azu** [comment]
closed by #3
